### ISSUE TITLE
ECR wrong documentation

### ISSUE THREAD

**Issue by alessandro-c** [drone/drone-plugin-index#121]
Hi everyone,

there are a couple of things that should be amended in the ECR plugin doc.

1)
As the current documentation state I was using something like :
```yaml
ecr:
    image: plugins/ecr
    repo: <account_id>.dkr.ecr.us-east-1.amazonaws.com/bar
    registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
```

althoug the tag/push commands translate to : 
```bash
/usr/local/bin/docker tag bb428deefa5c67967bcf86f6e2b68c6af94e0005 <account_id>.dkr.ecr.us-east-1.amazonaws.com/<account_id>.dkr.ecr.us-east-1.amazonaws.com/bar:latest

/usr/local/bin/docker push bb428deefa5c67967bcf86f6e2b68c6af94e0005 <account_id>.dkr.ecr.us-east-1.amazonaws.com/<account_id>.dkr.ecr.us-east-1.amazonaws.com/bar:latest
```
Now I don't know whether is the expected behaviour or a bug in the actual ECR plugin.

To fix the issue :
```yaml
ecr:
    image: plugins/ecr
    repo: bar
    registry: <account_id>.dkr.ecr.us-east-1.amazonaws.com
```
2)
Again, this could be a bug in the plugin I'm not sure, but here's what happens having the stage below, please note the **eu-west-2**

```yaml
ecr:
    image: plugins/ecr
    repo: bar
    registry: <account_id>.dkr.ecr.eu-west-2.amazonaws.com
```

```bash
# note us-east-1
# same applies to the the push command
/usr/local/bin/docker tag 3a43c236d8aada534f4a6f2ddb1d46a5e4d6edbe <account_id>.dkr.ecr.us-east-1.amazonaws.com/bar:latest
```
Unless otherwise specified looks like is completely ignoring the full registry uri and defaulting the region to us-east-1.

To prevent this from happening the region must be specified:
```yaml
ecr:
    image: plugins/ecr
    repo: bar
    registry: <account_id>.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
```
