### ISSUE TITLE
"Need to set username"

### ISSUE THREAD

**Issue by larssy1** [drone/drone-plugin-index#128]
Hi,

I've come across this plugin on drone.io.

I've set up a pipeline and I wanted to output to my website through FTP(S).
However, for some reason this plugin keeps throwing me the error "Need to set username".

Attempts:

Using the secrets array as posted as an example on GitHub.

```
deploy_develop:
    image: cschlosser/drone-ftps
    hostname: ftp.example.com:21
    secrets: [ hello_hapi@example.com, mypassword123 ]
    secure: true
    ssl_allow: true
    #secrets: [ftp_username,ftp_password]
    dest_dir: /public_html/beta/hello_hapi/
    src_dir: /build/
    when:
      branch: develop
```
And also tried with a seperate username
```
deploy_develop:
    image: cschlosser/drone-ftps
    username: hello_hapi@example.com
    hostname: ftp.example.com:21
    secrets: [ mypassword123 ]
    secure: true
    ssl_allow: true
    #secrets: [ftp_username,ftp_password]
    dest_dir: /public_html/beta/hello_hapi/
    src_dir: /build/
    when:
      branch: develop
```
Any idea what I'm doing wrong? I have no clue how to fix this, and I'm getting no results from Google.

Kind Regards,
Lars
