### ISSUE TITLE
demo in plugins/slack documents maybe need fix

### ISSUE THREAD

**Issue by tgly307** [drone/drone-plugin-index#146]
I did the test with the following example as document shows:
```
pipeline:
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/...
    channel: dev
```
but drone throw error: `Post : unsupported protocol scheme ""`
And I change drone setting as this:
```
pipeline:
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: dev
```
and it works.
So I suspect that the document is somewhat outdated, such as webhook must be written in secrets
