### ISSUE TITLE
Slack template does not work

### ISSUE THREAD

**Issue by Nakira** [drone/drone-plugin-index#217]
Hello,

here is my drone.yml file:
```yml
pipeline:
  slack:
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      link_names: true
      template: >
        {{#success build.status}}
          Website build {{build.number}} succeeded. See at http://example
        {{else}}
          Website build {{build.number}} failed. Fix me please. <@channelname> <@{{build.author}}>
        {{/success}}
    secrets: [ slack_webhook ]
    when:
      branch: testing
```

But i get the default message :
![image](https://user-images.githubusercontent.com/3797348/59552123-270a8780-8f83-11e9-9150-41dd1d169a78.png)
