### ISSUE TITLE
Docker Plugin parse error

### ISSUE THREAD

**Issue by vstepko** [drone/drone-plugin-index#293]
Hi, could somebody help me, please?
I try to build and publish my image to a private docker registry:

```YML
kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ****
    password: ****
    repo: https://*****.com:5000/myfirstimage
    registry: https://*****.com:5000
    tags:
    - latest
```

But got the next error:

```shell
Error parsing reference: "https://*****.com:5000/myfirstimage:latest" is not a valid repository/tag: invalid reference format
15921	time="2020-10-18T17:52:20Z" level=fatal msg="exit status 1"
```

But, when I try to push manually, all is ok.
What am I doing wrong? Will be grateful for any help.
