### ISSUE TITLE
How Can I use `commands` and `settings` on the docker plugin?

### ISSUE THREAD

**Issue by xx10n31y** [drone/drone-plugin-index#351]
Cause my docker registry's auth method need to execute `docker login` command, so my `.drone.yml` like this:
```yml
- name: publish
  image: plugins/docker
  pull: if-not-exists
  commands:
  - like docker login operates
  settings:
    registry: my custom registry
    repo: my custom repo
    autotag: true
    username:
      from_secret: coding-docker-username
    password:
      from_secret: coding-docker-password
    tags:
    - 1.1.0

```
If I add `commands` section, the `settings` section will not working
