### ISSUE TITLE
Half template references not working

### ISSUE THREAD

**Issue by RoTour** [drone/drone-plugin-index#371]
Hi, I've been trying to use this plugin for a while and couldn't figure why some of the template references just doesn't work
So I tried all of them to see if I was doing something wrong using this config
```yaml
  - name: discord notification
    image: appleboy/drone-discord
    when:
      status:
        - success
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        Info: {{build.message}}
        Version {{build.version}}
        owner : {{repo.owner}}
        name : {{repo.name}}
        status : {{build.status}}
        event : {{build.event}}
        number : {{build.number}}
        commit : {{build.commit}}
        message : {{build.message}}
        branch : {{build.branch}}
        tag : {{build.tag}}
        ref : {{build.ref}}
        author : {{build.author}}
        link : {{build.link}}
        started : {{build.started}}
        finished : {{build.finished}}
```

The ones working are :
- build.name
- build.status
- build.event
- build.number
- build.link
- build.started
- build.finished

All the other ones are returning nothing, am I doing something wrong or is something broken ?
